server:
  port: 2801

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: gateway_api_route
          uri: http://localhost:8080
          predicates:
            - Path=/gateway_api/**
          filters:
            - RewritePath=/gateway_api/(?<segment>.*), /$\{segment}
        - id: gateway_ws_api_route
          uri: ws://localhost:8081
          predicates:
            - Path=/gateway_ws_api/**
          filters:
            - RewritePath=/gateway_ws_api/(?<segment>.*), /$\{segment}
      httpclient:
        websocket:
          max-frame-payload-length: 65536
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "*"
            maxAge: 3600
